//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.18 at 07:32:38 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://streetshirt.xyz/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xyz.streetshirt.soap;
